name: satyam
on:
  workflow_dispatch:
jobs:
  my_job:
    name: deploy
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.0.0
    - name: linux
      run: whoami
